### ISSUE TITLE
CocoaPods support

### ISSUE THREAD

**Issue by ikovalisko** [icecreamstudios/ICSStyleManager#4]
Hi!

As I know for now the main blocker to introduce podspec is that `DDMathParser` also doesn't support CocoaPods. Unfortunately author doesn't consider it in near future (davedelong/DDMathParser#47).

For now I'm using private spec repo to solve issues with both libraries.
Here is podspec for ICSStyleManager:
``` ruby

Pod::Spec.new do |s|
  s.name = "ICSStyleManager"
  s.version = "1.0.1"
  s.summary = "ICSStyleManager is a lightweight iOS theming library"

  s.description  = <<-DESC
                  ICSStyleManager is a lightweight iOS library that lets you handily separate your app's font, color and other UI-related values into style sheet files that are both easy to read and straightforward to write.
                  ICSStyleManager's main goals are *simplicity* and *effectiveness*:
                  - *Simplicity*, because we didn't want to bloat our own code too much for such a simple task, thus we kept ICSStyleManager minimal for easy code readability and maintenance.
                  - *Effectiveness*, because we designed ICSStyleManager to facilitate real-world use cases minimizing additional hassle.
                  We are using ICSStyleManager in our app [Stories](http://stories.icecreamstudios.com).
                   DESC

  s.homepage = "https://github.com/icecreamstudios/ICSStyleManager"
  s.license = 'MIT'
  s.author = { "Ludovico Rossi" => "opensource@icecreamstudios.com" }

  s.platform = :ios, '7.0'
  s.requires_arc = true

  s.source = { :git => "https://github.com/icecreamstudios/ICSStyleManager.git", :commit => "fff8be0ed3751db4e6d27bd7890d9dad4b691d57" }
  
  s.source_files = 'Source', 'Source/**/*.{h,m}'
  s.exclude_files = 'Source/Libraries'

  s.dependency 'DDMathParser', "~> 1.0.1" # requires proper spec in private Spce repo

end

```

**Comment by ikovalisko** [comment]
@lrossi `DDMathParser` is now officially available on CocoaPods. Would you be so kind to submit the spec to trunk?

**Comment by lrossi** [comment]
I slightly updated the library to improve the compatibility with Xcode 7.1 and iOS 9, with the intent of creating a pod. However, I wasn't able to properly add `DDMathParser` as a dependency since it has been entirely rewritten in Swift and doesn't seem to be compatible with Objective-C (for instance, the `Expression` class does not inherit from `NSObject` nor it is declared with the `@objc` attribute).

Unfortunately, there seems to be a pod only for the latest (Swift) version of`DDMathParser`. I manually updated the dependency to version `1.1`, that in my understanding seems to be the last version of `DDMathParser` supporting Objective-C.
